import NetInfo from '@react-native-community/netinfo';
import { ApiClientError } from '@perum/api-client';
import { useQueryClient } from '@tanstack/react-query';
import { createContext, useContext, useEffect, useRef, useState, type PropsWithChildren } from 'react';
import { AppState } from 'react-native';
import { useAuth } from '../auth/AuthProvider';
import { useCapabilities } from '../auth/CapabilityProvider';
import { adminSupportInvalidationKeys, queryKeys } from '../query/queryKeys';
import { adminTicketActionPath, adminTicketActionPayload, adminTicketReadPath, adminTicketReplyPath, canUseAdminSupport, type AdminTicketAction } from './adminCore';
import { createAdminActionOutbox, type AdminActionMutation, type AdminActionResult } from './adminActionOutboxCore';
import { sqliteAdminActionOutbox } from './sqliteAdminActionOutbox';
import { createSupportOutboxCore, type SupportSendResult } from './outboxCore';
import { sqliteAdminReplyOutbox } from './sqliteAdminReplyOutbox';
import { createSupportReadCursorOutboxCore, type SupportReadResult } from './readCursorOutboxCore';
import { sqliteAdminReadCursorOutbox } from './sqliteAdminReadCursorOutbox';
import { supportMessageCreatePayload, supportReadPayload, type SupportMessage, type SupportMutation, type SupportReadMutation, type SupportTicket } from './types';

type Core = ReturnType<typeof createAdminActionOutbox>;
type ReplyCore = ReturnType<typeof createSupportOutboxCore>;
type ReadCore = ReturnType<typeof createSupportReadCursorOutboxCore>;
const Context = createContext<{ pending: AdminActionMutation[]; pendingReplies: SupportMutation[]; pendingReads: SupportReadMutation[]; enqueue(ticketId: string, expectedVersion: number, action: AdminTicketAction): Promise<void>; enqueueReply(ticketId: string, body: string): Promise<void>; markRead(ticketId: string, messageId: string): Promise<void>; retryReply(id: string): Promise<void>; retryRead(id: string): Promise<void>; discard(id: string): Promise<void> } | null>(null);
export function AdminActionProvider({ children }: PropsWithChildren) {
  const { account, apiClient } = useAuth(); const { has } = useCapabilities(); const enabled = canUseAdminSupport(account?.user.role, has('support_admin')); const enabledRef = useRef(enabled); enabledRef.current = enabled; const queryClient = useQueryClient(); const coreRef = useRef<Core | null>(null); const replyCoreRef = useRef<ReplyCore | null>(null); const readCoreRef = useRef<ReadCore | null>(null); const [pending, setPending] = useState<AdminActionMutation[]>([]); const [pendingReplies, setPendingReplies] = useState<SupportMutation[]>([]); const [pendingReads, setPendingReads] = useState<SupportReadMutation[]>([]);
  useEffect(() => {
    if (!account || !apiClient || !enabled) { coreRef.current = null; setPending([]); return; }
    let alive = true; const accountId = account.id; const refresh = async () => { const rows = await sqliteAdminActionOutbox.getByAccount(accountId); if (alive) setPending(rows); };
    const core = createAdminActionOutbox({ store: sqliteAdminActionOutbox, canSend: () => enabledRef.current, send: async item => { try { const payload = adminTicketActionPayload(item.action, item.expectedVersion, item.id); const ticket = item.action.kind === 'assignment' ? await apiClient.post<SupportTicket>(adminTicketActionPath(item.ticketId, item.action), payload) : await apiClient.patch<SupportTicket>(adminTicketActionPath(item.ticketId, item.action), payload); return { type: 'success', ticket } as AdminActionResult; } catch (error) { if (!(error instanceof ApiClientError)) return { type: 'transport', message: error instanceof Error ? error.message : undefined }; const detail = (error.originalErrorData as { detail?: { code?: unknown } })?.detail; return { type: 'http', status: error.status, code: typeof detail?.code === 'string' ? detail.code : undefined, message: error.message }; } }, onChange: refresh, onSuccess: async (_, ticket) => { queryClient.setQueryData(queryKeys.adminSupportTicket(accountId, ticket.id), ticket); await Promise.all(adminSupportInvalidationKeys.ticketChanged(accountId).map(queryKey => queryClient.invalidateQueries({ queryKey }))); }, onConflict: async () => { await Promise.all(adminSupportInvalidationKeys.ticketChanged(accountId).map(queryKey => queryClient.invalidateQueries({ queryKey }))); } });
    coreRef.current = core; const run = async () => { await core.run(accountId); await refresh(); }; void core.recover().then(run); void refresh(); const network = NetInfo.addEventListener(state => { if (state.isConnected !== false) void run(); }); const app = AppState.addEventListener('change', state => { if (state === 'active') void run(); }); const timer = setInterval(() => void run(), 5000); return () => { alive = false; network(); app.remove(); clearInterval(timer); };
  }, [account?.id, apiClient, enabled, queryClient]);
  useEffect(() => {
    if (!account || !apiClient || !enabled) { replyCoreRef.current = null; setPendingReplies([]); return; }
    let alive = true; const accountId = account.id; const refresh = async () => { const rows = await sqliteAdminReplyOutbox.getByAccount(accountId); if (alive) setPendingReplies(rows); };
    const core = createSupportOutboxCore({ store: sqliteAdminReplyOutbox, canSend: () => enabledRef.current, send: async item => { try { return { type: 'success', message: await apiClient.post<SupportMessage>(adminTicketReplyPath(item.ticketId), supportMessageCreatePayload(item)) } as SupportSendResult; } catch (error) { return error instanceof ApiClientError ? { type: 'http', status: error.status, message: error.message } : { type: 'transport', message: error instanceof Error ? error.message : undefined }; } }, onChange: refresh, onSuccess: async (_, ticketId) => { await Promise.all(adminSupportInvalidationKeys.replySent(accountId, ticketId).map(queryKey => queryClient.invalidateQueries({ queryKey }))); } });
    replyCoreRef.current = core; const run = async () => { await core.run(accountId); await refresh(); }; void core.recover().then(run); void refresh(); const network = NetInfo.addEventListener(state => { if (state.isConnected !== false) void run(); }); const app = AppState.addEventListener('change', state => { if (state === 'active') void run(); }); const timer = setInterval(() => void run(), 5000); return () => { alive = false; replyCoreRef.current = null; network(); app.remove(); clearInterval(timer); };
  }, [account?.id, apiClient, enabled, queryClient]);
  useEffect(() => {
    if (!account || !apiClient) { readCoreRef.current = null; setPendingReads([]); return; }
    if (!enabled) { readCoreRef.current = null; void sqliteAdminReadCursorOutbox.getByAccount(account.id).then(setPendingReads); return; }
    let alive = true; const accountId = account.id; const refresh = async () => { const rows = await sqliteAdminReadCursorOutbox.getByAccount(accountId); if (alive) setPendingReads(rows); };
    const core = createSupportReadCursorOutboxCore({ store: sqliteAdminReadCursorOutbox, canSend: () => enabledRef.current, send: async item => { try { await apiClient.post(adminTicketReadPath(item.ticketId), supportReadPayload(item)); return { type: 'success' } as SupportReadResult; } catch (error) { return error instanceof ApiClientError ? { type: 'http', status: error.status, message: error.message } : { type: 'transport', message: error instanceof Error ? error.message : undefined }; } }, onChange: refresh, onSuccess: async () => { await Promise.all(adminSupportInvalidationKeys.ticketRead(accountId).map(queryKey => queryClient.invalidateQueries({ queryKey }))); } });
    readCoreRef.current = core; const run = async () => { await core.run(accountId); await refresh(); }; void core.recover().then(run); void refresh(); const network = NetInfo.addEventListener(state => { if (state.isConnected !== false) void run(); }); const app = AppState.addEventListener('change', state => { if (state === 'active') void run(); }); const timer = setInterval(() => void run(), 5000); return () => { alive = false; readCoreRef.current = null; network(); app.remove(); clearInterval(timer); };
  }, [account?.id, apiClient, enabled, queryClient]);
  if (!account) return children; return <Context.Provider value={{ pending, pendingReplies, pendingReads, enqueue: async (ticketId, version, action) => { await coreRef.current?.enqueue(account.id, ticketId, version, action); void coreRef.current?.run(account.id); }, enqueueReply: async (ticketId, body) => { await replyCoreRef.current?.enqueue(account.id, ticketId, body); void replyCoreRef.current?.run(account.id); }, markRead: async (ticketId, messageId) => { await readCoreRef.current?.enqueue(account.id, ticketId, messageId); void readCoreRef.current?.run(account.id); }, retryReply: async id => { await replyCoreRef.current?.retry(account.id, id); }, retryRead: async id => { await readCoreRef.current?.retry(account.id, id); }, discard: async id => { await coreRef.current?.discard(account.id, id); } }}>{children}</Context.Provider>;
}
export function useAdminActionSync() { const value = useContext(Context); if (!value) throw new Error('AdminActionProvider is missing'); return value; }
